spring.application.name=crudAPI
spring.datasource.url=jdbc:mysql://localhost:3306/g4?useSSL=false
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true